// 雨夜密室杀人案 - 剧情数据
const STORY_DATA = {
  "title": "雨夜密室杀人案",
  "suspects": [
    {"name":"老周","identity":"管家，在陈府服务二十年","motive":"被陈远山发现其长期贪污府内账目，面临被辞退和起诉的风险","alibi":"声称案发时在厨房准备夜宵，但监控显示他曾离开厨房约十五分钟","secret":"老周私下与园丁刘师傅有秘密交易，帮助刘师傅走私珍稀植物。陈远山曾暗示已掌握证据。"},
    {"name":"陈夫人","identity":"陈远山之妻，名媛出身","motive":"是陈远山高额人身保险的唯一受益人（保额五千万），且婚姻名存实亡","alibi":"声称整晚在大厅看电视，但女佣表示曾在书房附近听到她的声音","secret":"陈夫人与商业对手赵明辉有秘密往来，两人曾多次在私密场合会面。陈远山似乎有所察觉。"},
    {"name":"赵明辉","identity":"明辉集团总裁，陈远山的商业对手","motive":"陈远山刚刚拒绝了他提出的并购方案，导致其公司面临巨大损失","alibi":"声称当晚在客房休息，但客房窗外的泥地上有新鲜脚印通往书房方向","secret":"赵明辉当晚曾偷偷潜入书房，试图窃取并购相关文件。他坚称自己离开时陈远山还活着。"},
    {"name":"刘师傅","identity":"陈府园丁，负责花园和温室","motive":"被陈远山威胁要解雇——陈远山发现他利用温室种植违禁植物","alibi":"声称整晚在花园工具房修理设备，但工具房内发现了一把沾有泥土的新鲜铲子","secret":"刘师傅与管家老周是秘密交易的搭档。他当晚确实离开过工具房，但声称是去花园巡查。"},
    {"name":"神秘访客","identity":"不明身份者，当晚曾出现在陈府附近","motive":"不明——此人身份成谜，但似乎与陈远山的过去有某种联系","alibi":"无人知晓此人的存在，只有花园外发现的一枚陌生鞋印和半截香烟","secret":"此人实为陈远山二十年前商业欺诈案的受害者家属，多年来一直在暗中调查陈远山。"}
  ],
  "scenes": [
    {"id":1,"location":"陈氏豪宅·大厅","atmosphere":"紧张","description":"暴雨如注的深夜，你接到紧急电话赶到陈氏豪宅。推开沉重的橡木大门，大厅灯火通明，水晶吊灯的光芒在雨夜中显得格外刺眼。空气中弥漫着一股淡淡的苦杏仁味，令人不安。\n\n陈远山的尸体躺在二楼书房密室内，据初步报告，门从内部反锁——这是一个完美的密室。\n\n管家老周面色苍白地站在楼梯口，双手微微发抖。陈夫人裹着丝绸披肩坐在沙发上低声啜泣，眼泪似乎是真的。商业伙伴赵明辉则焦急地在窗边踱步，时不时看一眼手表。\n\n你是警探林正，现在必须在天亮之前找出真相。","is_random":0,"is_ending":0,"choices":[
      {"text":"立即前往二楼检查密室和尸体，收集现场证据","target_scene":2,"hp_change":-3,"clue_change":15,"item_gain":"初步尸检记录","item_required":"","is_hidden":0,"hidden_min_clue":0},
      {"text":"先盘问在场的三位嫌疑人，了解基本情况","target_scene":3,"hp_change":-3,"clue_change":8,"item_gain":"","item_required":"","is_hidden":0,"hidden_min_clue":0},
      {"text":"搜查整栋豪宅，寻找异常痕迹和隐藏线索","target_scene":4,"hp_change":-5,"clue_change":12,"item_gain":"花园泥土样本","item_required":"","is_hidden":0,"hidden_min_clue":0}
    ]},
    {"id":2,"location":"二楼·书房密室","atmosphere":"悬疑","description":"你走上旋转楼梯来到二楼书房。厚重的红木门虚掩着，门锁有明显被撬过的痕迹——但管家说发现尸体时门是从内部反锁的。\n\n书房内一片狼藉：文件散落一地，书桌上的威士忌酒杯被打翻，酒液浸湿了地毯。陈远山的尸体仰躺在皮椅上，面色青紫，嘴唇发黑——典型的中毒症状。\n\n法医初步判断死亡时间在晚上10点到11点之间。尸体旁边有一个摔碎的小药瓶，标签已被撕去。书桌抽屉被拉开，里面的文件似乎被人翻动过。\n\n窗外的暴雨敲打着玻璃，一道闪电划过，你注意到窗台上有半个模糊的泥脚印。","is_random":0,"is_ending":0,"choices":[
      {"text":"仔细检查尸体和毒药瓶，寻找中毒来源","target_scene":5,"hp_change":-3,"clue_change":12,"item_gain":"毒药瓶碎片","item_required":"","is_hidden":0,"hidden_min_clue":0},
      {"text":"检查窗台上的泥脚印和书房内的物品","target_scene":6,"hp_change":-3,"clue_change":10,"item_gain":"指纹报告","item_required":"","is_hidden":0,"hidden_min_clue":0},
      {"text":"调查书桌抽屉中被翻动的文件","target_scene":7,"hp_change":-3,"clue_change":15,"item_gain":"账本记录","item_required":"","is_hidden":0,"hidden_min_clue":0}
    ]},
    {"id":3,"location":"陈氏豪宅·大厅","atmosphere":"紧张","description":"你决定先与在场的嫌疑人交谈，建立初步印象。\n\n管家老周主动走上前，声音颤抖地说：\"警探，我在陈府服务二十年了，从未出过这种事。老爷虽然严厉，但我不可能...\"他说到一半便哽咽了。\n\n陈夫人抬起头，眼眶红肿：\"请务必找到凶手。远山他虽然...有些事瞒着我，但他不该这样死去。\"她的手指紧紧攥着披肩边缘。\n\n赵明辉停下踱步，皱眉道：\"我和老陈只是商业上的分歧，没必要杀人。我今晚一直在客房，什么都不知道。\"他的语气过于急切。\n\n你注意到三人各自的表现——有人悲伤，有人紧张，有人似乎在刻意强调自己的无辜。","is_random":0,"is_ending":0,"choices":[
      {"text":"深入盘问管家老周，追问他的不在场证明","target_scene":8,"hp_change":-5,"clue_change":10,"item_gain":"","item_required":"","is_hidden":0,"hidden_min_clue":0},
      {"text":"单独与陈夫人谈话，了解夫妻关系","target_scene":9,"hp_change":-3,"clue_change":8,"item_gain":"","item_required":"","is_hidden":0,"hidden_min_clue":0},
      {"text":"质问赵明辉关于并购纠纷和当晚行踪","target_scene":10,"hp_change":-5,"clue_change":12,"item_gain":"","item_required":"","is_hidden":0,"hidden_min_clue":0}
    ]},
    {"id":4,"location":"陈氏豪宅·走廊与花园","atmosphere":"调查","description":"你决定先不惊动任何人，独自在豪宅中搜查。穿过长廊时，你注意到墙上挂着的家族照片中，陈远山总是表情严肃，而陈夫人则神情疏离。\n\n在厨房后门，你发现了一个新鲜的湿泥脚印——今晚暴雨，如果有人从外面进来，一定会留下痕迹。你顺着脚印来到花园。\n\n花园深处，温室里的灯光还亮着。透过玻璃，你看到一个中年男子正在整理工具——这应该是园丁刘师傅。他注意到你的目光，停下了手中的活。\n\n在花园围墙外，你还发现了一枚不属于任何家庭成员的陌生鞋印，以及半截被雨水浸湿的香烟。","is_random":0,"is_ending":0,"choices":[
      {"text":"进入温室盘问园丁刘师傅","target_scene":11,"hp_change":-5,"clue_change":10,"item_gain":"花园泥土样本","item_required":"","is_hidden":0,"hidden_min_clue":0},
      {"text":"仔细调查花园围墙外的陌生鞋印和烟蒂","target_scene":12,"hp_change":-5,"clue_change":15,"item_gain":"神秘访客线索","item_required":"","is_hidden":0,"hidden_min_clue":0}
    ]},
    {"id":5,"location":"书房密室·尸体旁","atmosphere":"危险","description":"你戴上手套，小心地检查尸体。陈远山的面部呈现典型的氰化物中毒症状——面色青紫，瞳孔放大。死亡过程应该非常迅速，不超过三分钟。\n\n摔碎的药瓶碎片散落在地毯上，你小心地收集起来。瓶底残留着少量白色粉末，需要送检确认。但瓶身上没有任何标签，似乎被人刻意撕掉了。\n\n就在这时，你注意到尸体右手的指甲缝里有一些细微的纤维——可能是挣扎时从凶手衣服上抓下来的。\n\n突然，书房角落的旧钟\"当\"地响了一声，你被吓了一跳，心跳加速。（HP-3）","is_random":1,"is_ending":0,"choices":[
      {"text":"收集药瓶碎片送检，分析毒药成分","target_scene":13,"hp_change":-3,"clue_change":15,"item_gain":"毒药瓶碎片","item_required":"","is_hidden":0,"hidden_min_clue":0},
      {"text":"提取指甲缝中的纤维样本，寻找匹配来源","target_scene":14,"hp_change":-3,"clue_change":12,"item_gain":"纤维样本","item_required":"","is_hidden":0,"hidden_min_clue":0}
    ]},
    {"id":6,"location":"书房密室·窗台","atmosphere":"悬疑","description":"你走到窗台前仔细查看那个泥脚印。鞋印纹路清晰，大约43码，鞋底有独特的菱形花纹——这不是普通的皮鞋，更像是户外登山鞋。\n\n书桌上散落着几份文件：一份未签完的并购协议，一份管家老周的账目审计报告（上面用红笔标注了好几处异常），还有一封字迹潦草的匿名举报信。\n\n举报信的内容让你心头一紧：\"陈远山，你二十年前做的事，不会就这么算了。\"落款处没有名字，只有一个奇怪的符号。\n\n你用指纹粉在酒杯上采集到了几枚清晰的指纹——需要与嫌疑人比对。","is_random":0,"is_ending":0,"choices":[
      {"text":"将指纹送检，与在场所有人进行比对","target_scene":15,"hp_change":-3,"clue_change":15,"item_gain":"指纹报告","item_required":"","is_hidden":0,"hidden_min_clue":0},
      {"text":"深入调查匿名举报信的来源和符号含义","target_scene":16,"hp_change":-3,"clue_change":12,"item_gain":"神秘密信","item_required":"","is_hidden":0,"hidden_min_clue":0},
      {"text":"分析泥脚印的鞋底纹路，寻找匹配的鞋子","target_scene":17,"hp_change":-3,"clue_change":10,"item_gain":"鞋印拓片","item_required":"","is_hidden":0,"hidden_min_clue":0}
    ]},
    {"id":7,"location":"书房密室·书桌","atmosphere":"调查","description":"你拉开书桌抽屉，里面凌乱地堆放着各类文件。最上面是一本皮质封面的账本，翻开后发现管家老周的账目存在大量异常——连续数月有大额资金被转入一个不明账户。\n\n抽屉深处还有一个上锁的暗格。你用工具小心撬开后，里面放着一把保险箱钥匙和一份遗嘱草稿。遗嘱中，陈远山似乎有意将大部分财产捐给慈善机构，而非留给妻子。\n\n另外，你还找到了一叠照片——是陈夫人与赵明辉在不同场合的亲密合影。照片背面写着日期，最早的一张是三个月前。\n\n这些发现让案件的动机变得更加复杂。","is_random":0,"is_ending":0,"choices":[
      {"text":"深入调查管家老周的账目问题","target_scene":8,"hp_change":-5,"clue_change":10,"item_gain":"账本记录","item_required":"","is_hidden":0,"hidden_min_clue":0},
      {"text":"使用保险箱钥匙寻找隐藏的保险箱","target_scene":18,"hp_change":-5,"clue_change":15,"item_gain":"保险箱钥匙","item_required":"","is_hidden":0,"hidden_min_clue":0},
      {"text":"调查陈夫人与赵明辉的秘密关系","target_scene":9,"hp_change":-3,"clue_change":8,"item_gain":"秘密照片","item_required":"","is_hidden":0,"hidden_min_clue":0}
    ]},
    {"id":8,"location":"厨房·管家盘问","atmosphere":"紧张","description":"你将管家老周带到厨房单独谈话。他紧张地擦拭着已经一尘不染的料理台。\n\n\"老周，你声称案发时一直在厨房准备夜宵，但监控显示你离开过厨房约十五分钟。那段时间你在哪里？\"\n\n老周的手明显抖了一下：\"我...我去了趟地下室检查酒窖。老爷每晚睡前都要喝一杯威士忌，我只是去取酒...\"\n\n\"但我们在地下室发现了一个被撬开的保险箱。\"你试探道。\n\n老周的脸色瞬间变得惨白。沉默良久，他才开口：\"警探，我可以解释。但这事...这事和老爷的死没有关系。\"\n\n他声称保险箱里的东西——一份关于刘师傅在温室种植违禁植物的调查报告——是他受陈远山指使去调查的。","is_random":0,"is_ending":0,"choices":[
      {"text":"相信老周的解释，转而调查刘师傅","target_scene":11,"hp_change":-3,"clue_change":5,"item_gain":"","item_required":"","is_hidden":0,"hidden_min_clue":0},
      {"text":"不相信老周，继续追问保险箱和贪污的事","target_scene":19,"hp_change":-10,"clue_change":15,"item_gain":"管家供词","item_required":"","is_hidden":0,"hidden_min_clue":0}
    ]},
    {"id":9,"location":"客厅·陈夫人谈话","atmosphere":"悬疑","description":"你请陈夫人到客厅角落的沙发上单独交谈。她擦干眼泪，但眼神闪烁不定。\n\n\"陈夫人，请恕我直言——您和您丈夫的关系如何？\"\n\n她沉默了一会儿：\"远山他...是个工作狂。我们的婚姻早就名存实亡了。他整天忙于生意，而我...\"她欲言又止。\n\n\"您知道他最近修改了遗嘱吗？他将大部分财产捐给了慈善机构。\"\n\n陈夫人的表情瞬间僵硬。\"什么？这不可能！\"她的声音提高了八度。\n\n\"还有一件事——您和赵明辉先生的关系，能解释一下吗？\"你拿出了那些照片。\n\n她看着照片，嘴唇颤抖：\"这...这不能说明什么。我们是朋友。只是朋友。\"但她的眼睛出卖了她。","is_random":0,"is_ending":0,"choices":[
      {"text":"温柔追问，试图让她主动说出真相","target_scene":20,"hp_change":-3,"clue_change":12,"item_gain":"","item_required":"","is_hidden":0,"hidden_min_clue":0},
      {"text":"严厉质问，施压迫使她交代与赵明辉的合谋","target_scene":10,"hp_change":-5,"clue_change":8,"item_gain":"","item_required":"","is_hidden":0,"hidden_min_clue":0}
    ]},
    {"id":10,"location":"客房·盘问赵明辉","atmosphere":"紧张","description":"赵明辉带你来到他当晚所在的客房。房间整洁得像是没人住过，床铺几乎没有皱褶。\n\n\"赵先生，你和陈远山的并购谈判破裂了，对吧？如果并购失败，你的公司将面临多大损失？\"\n\n赵明辉扯了扯领带：\"大约三千万。但这不足以让我杀人。\"\n\n\"你和陈夫人的关系呢？\"你突然抛出这个问题。\n\n他明显愣住了。\"什么关系？我们是...商业上的朋友。\"\n\n\"那为什么她手机里有你深夜发来的信息？内容是'今晚必须解决这件事'。\"\n\n赵明辉的额头渗出汗珠：\"那条信息说的是...并购的事。我是指并购！\"\n\n\"你当晚离开过客房吗？窗外的泥地上有你的脚印。\"\n\n他瘫坐在床上：\"好吧，我确实出去过。我去书房想再和远山谈谈并购的事...但我发誓，我离开的时候他还活着！\"","is_random":0,"is_ending":0,"choices":[
      {"text":"暂时相信赵明辉，继续调查其他线索","target_scene":4,"hp_change":-5,"clue_change":5,"item_gain":"","item_required":"","is_hidden":0,"hidden_min_clue":0},
      {"text":"将赵明辉列为重点嫌疑人，申请搜查他的随身物品","target_scene":21,"hp_change":-5,"clue_change":15,"item_gain":"赵明辉的公文包","item_required":"","is_hidden":0,"hidden_min_clue":0}
    ]},
    {"id":11,"location":"花园·温室","atmosphere":"调查","description":"你推开温室的玻璃门，潮湿的暖风扑面而来。刘师傅正在整理一排盆栽，看到你后停下了手中的活。\n\n\"刘师傅，这么晚了还在工作？\"\n\n\"习惯了，警探。植物不会等人。\"他的回答简短而平静。\n\n\"你知道陈远山先生打算解雇你吗？\"\n\n刘师傅的手停在半空，沉默了几秒：\"知道。但这不是我杀人的理由。我有手艺，在哪里都能找到工作。\"\n\n\"那你能解释一下，为什么工具房里有一把沾着新鲜泥土的铲子？今晚暴雨，你不会是在花园里干活吧？\"\n\n刘师傅的眼神闪烁了一下：\"我...我只是在整理工具。\"\n\n你注意到温室角落里有几个被遮住的盆栽——叶片形状异常，似乎不是普通观赏植物。","is_random":1,"is_ending":0,"choices":[
      {"text":"检查温室角落的可疑盆栽","target_scene":22,"hp_change":-5,"clue_change":15,"item_gain":"违禁植物样本","item_required":"","is_hidden":0,"hidden_min_clue":0},
      {"text":"追问刘师傅与管家老周的秘密交易","target_scene":19,"hp_change":-5,"clue_change":10,"item_gain":"","item_required":"","is_hidden":0,"hidden_min_clue":0},
      {"text":"搜查工具房，寻找可能的凶器线索","target_scene":23,"hp_change":-3,"clue_change":12,"item_gain":"花园工具清单","item_required":"","is_hidden":0,"hidden_min_clue":0}
    ]},
    {"id":12,"location":"花园围墙外·暗巷","atmosphere":"危险","description":"你循着泥地上的陌生鞋印来到花园围墙外。这里是一条偏僻的暗巷，路灯昏暗，雨水沿着墙壁流淌。\n\n鞋印在围墙下停留了很久——这个人在此徘徊过相当长的时间。你在墙角发现了几根被雨水浸湿的香烟烟蒂，品牌是市面上少见的进口烟。\n\n更令人不安的是，你发现围墙上有一处攀爬的痕迹——墙头的铁栅栏被掰弯了一根，缝隙刚好容一人侧身通过。墙内侧的花坛泥土上，同样有那个陌生鞋印。\n\n这个人不仅来过，而且进入了豪宅内部。\n\n一阵冷风吹过，你感到后颈发凉。这个人是否还在附近？（HP-3）","is_random":1,"is_ending":0,"choices":[
      {"text":"采集烟蒂和鞋印样本，回警局做技术分析","target_scene":24,"hp_change":-5,"clue_change":15,"item_gain":"神秘访客线索","item_required":"","is_hidden":0,"hidden_min_clue":0},
      {"text":"冒险追踪暗巷，试图找到神秘访客【高风险：可能遭遇暗杀】","target_scene":25,"hp_change":-30,"clue_change":20,"item_gain":"神秘访客的烟盒","item_required":"花园泥土样本","is_hidden":1,"hidden_min_clue":30,"required_visited":[11]}
    ]},
    {"id":13,"location":"法医实验室","atmosphere":"调查","description":"你将毒药瓶碎片送到临时搭建的法医分析站。技术人员在显微镜下仔细检查后，给出了初步报告。\n\n\"警探，瓶内残留的白色粉末是氰化钾——剧毒，微量即可致死。但有意思的是，瓶身上检测到了两种不同的指纹。\"\n\n\"两种？\"\n\n\"对。一组属于管家老周——这很合理，他负责打理酒水和药品。但另一组...属于园丁刘师傅。这就奇怪了，园丁一般不会接触到书房里的东西。\"\n\n此外，瓶底的标签残留显示这瓶药原本是陈远山的处方安眠药——有人将安眠药换成了毒药。\n\n这个发现让案情出现了重大转折。","is_random":0,"is_ending":0,"choices":[
      {"text":"将管家老周列为第一嫌疑人，立即进行逮捕前审讯","target_scene":19,"hp_change":-5,"clue_change":5,"item_gain":"","item_required":"","is_hidden":0,"hidden_min_clue":0},
      {"text":"继续调查园丁刘师傅，追问他为何指纹出现在药瓶上","target_scene":22,"hp_change":-5,"clue_change":10,"item_gain":"毒药分析报告","item_required":"","is_hidden":0,"hidden_min_clue":0},
      {"text":"暂不下结论，调查谁有渠道获取氰化钾","target_scene":26,"hp_change":-3,"clue_change":12,"item_gain":"氰化物来源线索","item_required":"","is_hidden":0,"hidden_min_clue":0}
    ]},
    {"id":14,"location":"法医实验室","atmosphere":"调查","description":"法医小心地从死者指甲缝中提取了纤维样本。在显微镜下观察后，法医的眉头皱了起来。\n\n\"这些纤维很特殊——是粗花呢面料的纤维，含有一种罕见的植物染料。这种面料不常见，通常是高端定制西装才会使用。\"\n\n\"能确定具体来源吗？\"\n\n\"粗花呢西装在本地只有两家裁缝店制作。我可以帮你查一下最近的订单记录。另外，纤维上还附着了一些土壤颗粒——这种土壤的矿物质成分与普通花园土不同，更像是温室专用培养土。\"\n\n温室培养土——这又把线索指向了花园。","is_random":0,"is_ending":0,"choices":[
      {"text":"调查本地裁缝店的粗花呢西装定制记录","target_scene":27,"hp_change":-3,"clue_change":12,"item_gain":"西装定制记录","item_required":"","is_hidden":0,"hidden_min_clue":0},
      {"text":"根据土壤线索再次前往花园温室调查","target_scene":22,"hp_change":-5,"clue_change":10,"item_gain":"","item_required":"","is_hidden":0,"hidden_min_clue":0}
    ]},
    {"id":15,"location":"警局·技术科","atmosphere":"调查","description":"指纹比对结果出来了。技术员将报告递给你时表情严肃。\n\n\"酒杯上有三个人的指纹：陈远山本人的（正常，他喝过酒）、管家老周的（也正常，他负责倒酒）、以及...赵明辉的。\"\n\n\"赵明辉的指纹出现在酒杯上？\"\n\n\"是的。而且指纹位置很特殊——是在杯口边缘，像是在倒酒或下药时留下的。另外，书桌上的文件上也检测到了赵明辉的指纹。\"\n\n\"老周呢？\"\n\n\"老周的指纹在药瓶碎片上也有——但这可以用他的职责来解释。我们需要更多证据。\"\n\n技术员补充道：\"哦对了，密室门锁上没有撬锁痕迹——要么凶手有钥匙，要么死者自己反锁了门。\"","is_random":0,"is_ending":0,"choices":[
      {"text":"重点调查赵明辉——他为何碰过酒杯和文件","target_scene":21,"hp_change":-5,"clue_change":10,"item_gain":"指纹比对报告","item_required":"","is_hidden":0,"hidden_min_clue":0},
      {"text":"调查密室反锁的真相——谁有可能持有钥匙","target_scene":28,"hp_change":-3,"clue_change":12,"item_gain":"钥匙调查记录","item_required":"","is_hidden":0,"hidden_min_clue":0}
    ]},
    {"id":16,"location":"警局·档案室","atmosphere":"悬疑","description":"你带着那封匿名举报信来到档案室。信上的符号引起了你的注意——那是一个被圆圈包围的三角形，像某种标记。\n\n档案管理员翻阅了二十年前的旧案卷宗。三个小时后，一份泛黄的文件被摆在你面前：二十年前，陈远山曾卷入一起商业欺诈案——他的公司以虚假合同骗取了一批小投资者的毕生积蓄。其中一位受害者名叫韩正清，在损失全部财产后自杀身亡。\n\n韩正清的遗孀和年幼的儿子从此下落不明。\n\n那个符号——正是韩正清当年公司的标志。\n\n你感到背脊发凉。二十年前的旧账，终于在今晚找上了门。","is_random":0,"is_ending":0,"choices":[
      {"text":"追查韩正清家属的下落，寻找神秘访客的真实身份","target_scene":29,"hp_change":-15,"clue_change":15,"item_gain":"神秘密信","item_required":"","is_hidden":0,"hidden_min_clue":0},
      {"text":"将此发现作为重要线索记录，先完成当前的调查","target_scene":2,"hp_change":-3,"clue_change":5,"item_gain":"旧案卷宗","item_required":"","is_hidden":0,"hidden_min_clue":0}
    ]},
    {"id":17,"location":"花园·围墙","atmosphere":"调查","description":"你拿着鞋印拓片回到花园，与发现的各个脚印进行对比。\n\n书房窗台上的泥脚印与花园中通往厨房后门的脚印是同一双鞋——43码，菱形花纹鞋底。而花园围墙外的陌生鞋印则完全不同——是一双41码的皮鞋，鞋底磨损严重。\n\n这意味着至少有两个人曾在案发时段出现在不该出现的地方。\n\n你回到大厅，请所有人脱下鞋子进行检查。赵明辉穿的正是一双43码的登山鞋，鞋底花纹与泥印完全吻合。而管家老周的皮鞋虽然尺码不同，但他的工作靴——藏在地下室楼梯间——却沾满了新鲜泥土。\n\n真相似乎在慢慢浮现，但又更加扑朔迷离。","is_random":0,"is_ending":0,"choices":[
      {"text":"确认赵明辉当晚确实去过书房——质问他","target_scene":21,"hp_change":-5,"clue_change":10,"item_gain":"鞋印比对报告","item_required":"","is_hidden":0,"hidden_min_clue":0},
      {"text":"调查管家的工作靴为何沾满泥土","target_scene":19,"hp_change":-5,"clue_change":8,"item_gain":"","item_required":"","is_hidden":0,"hidden_min_clue":0}
    ]},
    {"id":18,"location":"地下室·隐藏保险箱","atmosphere":"发现","description":"你用找到的钥匙打开了地下室角落的一个隐藏保险箱。门\"咔嗒\"一声弹开，里面存放的东西让你倒吸一口凉气。\n\n首先是一叠银行对账单——显示管家老周在过去两年中，从陈府账户转移了超过两百万到一个境外账户。其次是刘师傅签名的借条——他向老周借了一大笔钱，用途不明。\n\n但最关键的是第三样东西：一份DNA亲子鉴定报告。报告显示，陈远山并非其\"儿子\"的生物学父亲——那个孩子（现在在国外读书）的真正父亲是...赵明辉。\n\n这份报告标注日期是三天前。陈远山刚刚知道这个真相。\n\n如果这份报告的内容被公开，陈夫人和赵明辉的秘密关系将彻底暴露，而他们也将失去一切继承权。","is_random":0,"is_ending":0,"choices":[
      {"text":"拿着亲子鉴定报告质问陈夫人","target_scene":20,"hp_change":-5,"clue_change":15,"item_gain":"亲子鉴定报告","item_required":"","is_hidden":0,"hidden_min_clue":0},
      {"text":"将银行对账单作为老周贪污的铁证","target_scene":19,"hp_change":-5,"clue_change":10,"item_gain":"银行对账单","item_required":"","is_hidden":0,"hidden_min_clue":0}
    ]},
    {"id":19,"location":"地下室·审讯室","atmosphere":"紧张","description":"你将管家老周带到了地下室——这里暂时被用作临时审讯室。\n\n老周坐在椅子上，双手紧握。你将他贪污的证据摆在桌上：银行对账单、被篡改的账本、与刘师傅的秘密交易记录。\n\n\"老周，现在你能告诉我真相了吗？\"\n\n长久的沉默后，老周终于崩溃了。\n\n\"是，我贪污了。两百万。老爷三天前发现了，他给了我两个选择——要么一周内把钱全部还回来并自首，要么他会报警。我...我走投无路了。\"\n\n\"所以你杀了他？\"\n\n\"不！不是！\"老周猛地抬头，\"我是想过...但我没有！那天晚上，我是去书房求他再给我一次机会。但他不听，把我赶了出来。那时候他还活着！我发誓！\"\n\n\"那你为什么在药瓶上留下指纹？\"\n\n\"因为...因为那瓶安眠药是我按老爷吩咐放在他桌上的。每天晚上都是这样。但我发誓我放的是安眠药，不是毒药！\"","is_random":0,"is_ending":0,"choices":[
      {"text":"相信老周不是凶手，调查谁有机会调换药瓶","target_scene":26,"hp_change":-5,"clue_change":10,"item_gain":"管家供词","item_required":"","is_hidden":0,"hidden_min_clue":0},
      {"text":"认为老周嫌疑最大，准备正式逮捕","target_scene":30,"hp_change":-5,"clue_change":5,"item_gain":"","item_required":"","is_hidden":0,"hidden_min_clue":0}
    ]},
    {"id":20,"location":"客厅·最后盘问陈夫人","atmosphere":"紧张","description":"你回到客厅，陈夫人独自坐在沙发上。她的妆容已经花了，眼神中透着疲惫和恐惧。\n\n你将亲子鉴定报告放在她面前。她看了一眼，整个人像是被抽空了力气。\n\n\"你早就知道了，对吗？陈远山三天前拿到了这份报告。\"\n\n她的眼泪无声地滑落：\"是的...他知道了。他说要修改遗嘱，说一分钱都不会留给我和孩子。他说...他说要公开一切。\"\n\n\"所以你和赵明辉合谋杀了他？\"\n\n\"不！\"她摇头，\"明辉只是...他只是想和远山再谈谈并购的事。我们没想过杀人。真的没有！\"\n\n\"那你知道谁可能调换了药瓶吗？\"\n\n她犹豫了：\"老周...老周最恨远山。远山发现他贪污后，把他逼得很紧。但我也不知道...那天晚上，我看到一个黑影在书房窗外闪过。我以为是我眼花了...\"","is_random":0,"is_ending":0,"choices":[
      {"text":"追问窗外黑影的细节——那可能是神秘访客","target_scene":29,"hp_change":-5,"clue_change":15,"item_gain":"目击证词","item_required":"","is_hidden":0,"hidden_min_clue":0},
      {"text":"综合所有线索，准备做出最终推理【隐藏选项】","target_scene":31,"hp_change":-3,"clue_change":10,"item_gain":"","item_required":"亲子鉴定报告","is_hidden":1,"hidden_min_clue":50,"required_visited":[9,11]}
    ]},
    {"id":21,"location":"客房·搜查赵明辉","atmosphere":"紧张","description":"你对赵明辉的随身物品进行了彻底搜查。在他的公文包夹层中，你发现了关键证据——\n\n一份并购协议的副本，上面有陈远山拒绝签字的批注。批注旁边，赵明辉用红笔写了一个数字：\"5000万\"——这正是陈夫人保险的保额。\n\n此外，还有一份日期标注为昨晚的酒店入住记录——但记录显示他只订了一个房间，而非两个。这说明他原本计划当晚离开，但临时改变了主意。\n\n赵明辉还随身携带了一小瓶处方药——瓶身标签显示是强效安眠药，但里面的药片颜色与标签描述不符。你决定将这瓶药送去检测。\n\n\"赵先生，你的安眠药似乎被人调包了。你能解释一下吗？\"","is_random":0,"is_ending":0,"choices":[
      {"text":"将赵明辉的药瓶送检，比对毒药成分","target_scene":13,"hp_change":-5,"clue_change":15,"item_gain":"赵明辉的药瓶","item_required":"","is_hidden":0,"hidden_min_clue":0},
      {"text":"继续审问赵明辉关于保险金的事","target_scene":10,"hp_change":-10,"clue_change":8,"item_gain":"","item_required":"","is_hidden":0,"hidden_min_clue":0}
    ]},
    {"id":22,"location":"花园·温室深入调查","atmosphere":"发现","description":"你掀开遮盖的帆布，露出下面几排特殊的盆栽。这些植物的叶片形状奇特，茎干上还残留着白色粉末痕迹。\n\n\"这是什么？\"你问道。\n\n刘师傅的脸色变得苍白：\"这...这是实验性植物。只是观赏用的。\"\n\n\"别撒谎了。这种植物的根茎含有剧毒物质，可以被提炼为氰化物。\"\n\n刘师傅终于崩溃：\"是老周！老周让我种的！他说有人出高价收购这些植物提取物。我不知道他会用来...我真的不知道！\"\n\n\"老周让你种这些有多久了？\"\n\n\"半年。他每周来取一次提取物。上个月他突然说要增加产量，说有大客户。\"\n\n毒药的来源终于查清了——就来自这座花园。但使用者是谁？是老周本人，还是有人从他那里获取了毒药？","is_random":0,"is_ending":0,"choices":[
      {"text":"立即逮捕刘师傅，作为从犯审讯","target_scene":23,"hp_change":-15,"clue_change":10,"item_gain":"违禁植物样本","item_required":"","is_hidden":0,"hidden_min_clue":0},
      {"text":"拿着毒药来源的证据再次审问老周","target_scene":19,"hp_change":-5,"clue_change":15,"item_gain":"毒药来源证据","item_required":"","is_hidden":0,"hidden_min_clue":0}
    ]},
    {"id":23,"location":"花园·工具房","atmosphere":"调查","description":"工具房里弥漫着机油和泥土的味道。你在墙上找到了刘师傅的工具清单——每一件工具的位置都有标注。但铲子的位置是空的，而它本应挂在墙上。\n\n你在角落找到了那把铲子——上面沾着的新鲜泥土与书房窗台上发现的泥土成分一致。\n\n\"刘师傅，这把铲子上的泥土和书房窗台上的泥土是同一种。你能解释吗？\"\n\n刘师傅低着头：\"我...我确实去过书房附近。但那是晚上八点，老爷还活着！我只是去给走廊的盆栽换土。\"\n\n\"八点？但泥土还没干——说明你不久前才用过这把铲子。\"\n\n他无法回答。\n\n此外，你在工具房储物柜里发现了一张被揉皱的纸条，上面写着：\"今晚十点，花园后门见面。老周。\"","is_random":0,"is_ending":0,"choices":[
      {"text":"拿着纸条质问刘师傅——你和老周十点见面做了什么","target_scene":22,"hp_change":-10,"clue_change":12,"item_gain":"秘密纸条","item_required":"","is_hidden":0,"hidden_min_clue":0},
      {"text":"将铲子上的泥土样本送检，获取科学证据","target_scene":14,"hp_change":-3,"clue_change":10,"item_gain":"泥土比对报告","item_required":"","is_hidden":0,"hidden_min_clue":0}
    ]},
    {"id":24,"location":"警局·技术分析室","atmosphere":"调查","description":"技术员对烟蒂上的唾液进行了DNA提取，但数据库中没有匹配记录。鞋印分析结果显示这是一双41码的旧皮鞋，鞋底磨损不均匀——此人可能有轻微的跛足。\n\n通过香烟品牌追踪，这种进口烟在本地只有一个销售点——老城区的一家烟草专卖店。店主回忆说，昨天下午确实有一个陌生男子来买过这种烟。\n\n\"那人长什么样？\"\n\n\"三十多岁，瘦高个，走路有点跛。戴着帽子，看不清脸。他说普通话带外地口音。\"\n\n你将这个特征与韩正清儿子的年龄进行了比对——如果那个孩子还活着，现在应该正好三十多岁。\n\n一切都在指向同一个方向：二十年前的旧案，有人回来复仇了。","is_random":0,"is_ending":0,"choices":[
      {"text":"继续追踪神秘访客，前往老城区调查","target_scene":29,"hp_change":-15,"clue_change":15,"item_gain":"神秘访客画像","item_required":"","is_hidden":0,"hidden_min_clue":0},
      {"text":"先回到豪宅，将神秘访客的线索与现有证据整合【隐藏选项】","target_scene":31,"hp_change":-3,"clue_change":10,"item_gain":"","item_required":"神秘访客线索","is_hidden":1,"hidden_min_clue":40,"required_visited":[9,19]}
    ]},
    {"id":25,"location":"暗巷深处","atmosphere":"危险","description":"你决定冒险追踪暗巷。雨水模糊了视线，巷子越来越窄，路灯的光几乎照不到这里。\n\n前方传来急促的脚步声——有人！你加快脚步追了上去。\n\n在一个拐角处，你与一个黑影撞了个满怀。那人踉跄了一下，帽子掉落——露出一张三十多岁的瘦削面孔，左眼下方有一道旧伤疤。\n\n\"别跑！警察！\"你喊道。\n\n那人从口袋中掏出一个东西扔向你——是一个金属烟盒。你侧身躲过，但这一瞬间的延误让他拉开了一段距离。\n\n\"你也是来给陈远山陪葬的吗？\"那人回头冷笑了一声，然后消失在雨夜中。\n\n你捡起地上的烟盒——上面刻着那个熟悉的圆圈三角形符号。里面还有一张泛黄的照片，照片上是一个中年男子抱着一个小男孩。照片背面写着：\"爸爸，我一定会为你讨回公道。——韩\"","is_random":0,"is_ending":0,"choices":[
      {"text":"带着烟盒和照片返回豪宅，这可能是破案的关键","target_scene":24,"hp_change":-10,"clue_change":15,"item_gain":"决定性证据","item_required":"","is_hidden":0,"hidden_min_clue":0,"required_visited":[0]},
      {"text":"不顾警告继续追击神秘访客，拔枪上前抓捕【极度危险！】","target_scene":25,"hp_change":-100,"clue_change":0,"item_gain":"","item_required":"","is_hidden":0,"hidden_min_clue":0,"required_visited":[0]}
    ]},
    {"id":26,"location":"警局·物证分析室","atmosphere":"调查","description":"你决定从毒药来源入手。氰化钾是严格管控的危险化学品，普通人难以获取。但技术员给出了一个意外发现——\n\n\"这种氰化物的纯度不高，含有大量植物杂质。不是工业级别的，更像是...从天然植物中提取的。\"\n\n\"天然植物？\"\n\n\"是的。某些植物的根茎中含有氰苷，经过处理可以提炼出氰化物。具体来说，可能是木薯、苦杏仁，或者...某些特殊品种的月桂。\"\n\n月桂——花园温室里种植的正是各种植物。\n\n此外，技术员在分析药瓶残留时发现了一个细节：药瓶内壁有两种不同的残留层——说明有人先倒出了原来的安眠药，再装入毒药。但操作过程中留下了微量的中间层物质：威士忌。\n\n毒药是通过威士忌混合后装入药瓶的——而陈远山每晚都会喝威士忌。这意味着凶手非常了解陈远山的习惯。","is_random":0,"is_ending":0,"choices":[
      {"text":"根据植物线索调查温室和刘师傅","target_scene":22,"hp_change":-5,"clue_change":10,"item_gain":"毒药来源证据","item_required":"","is_hidden":0,"hidden_min_clue":0},
      {"text":"追查威士忌的线索——谁有机会在酒中下毒","target_scene":28,"hp_change":-5,"clue_change":12,"item_gain":"威士忌分析报告","item_required":"","is_hidden":0,"hidden_min_clue":0}
    ]},
    {"id":27,"location":"老城区·裁缝店","atmosphere":"调查","description":"你根据法医提供的纤维线索，找到了老城区唯一一家制作粗花呢西装的裁缝店。店主是一位头发花白的老裁缝。\n\n\"粗花呢西装？\"他推了推老花镜，\"最近三个月，我一共做了四套。\"他翻出订单记录：\n\n\"第一套是赵明辉先生的——深灰色粗花呢，三周前取的。\"\n\"第二套是陈远山先生本人的——棕色粗花呢，两个月前。\"\n\"第三套...\"他顿了顿，\"是一位不愿留全名的客人，只登记了姓韩。\"\n\n\"姓韩？！\"你的心跳加速了。\n\n\"对，三十多岁，有点跛。付的现金。\"\n\n第四套的订购者是管家老周——但他后来取消了订单，理由是\"暂时不需要了\"。\n\n粗花呢纤维可能来自三个人：赵明辉、陈远山本人（但不会在指甲缝里），或者那个姓韩的神秘访客。","is_random":0,"is_ending":0,"choices":[
      {"text":"确认赵明辉的西服——他案发当晚穿的就是粗花呢吗","target_scene":21,"hp_change":-5,"clue_change":10,"item_gain":"裁缝店记录","item_required":"","is_hidden":0,"hidden_min_clue":0},
      {"text":"追踪姓韩的神秘客人——他很可能就是神秘访客","target_scene":29,"hp_change":-15,"clue_change":15,"item_gain":"神秘访客西装记录","item_required":"","is_hidden":0,"hidden_min_clue":0}
    ]},
    {"id":28,"location":"书房·密室门锁调查","atmosphere":"悬疑","description":"你重新检查了密室的门锁。这是一把高级黄铜锁，没有撬锁痕迹——说明凶手要么有钥匙，要么是死者自己反锁了门。\n\n你询问了钥匙的持有情况。管家老周说只有三把钥匙：一把在陈远山身上（已在尸体口袋中找到），一把在管家处（老周出示了），还有一把备用钥匙通常放在大厅抽屉里。\n\n但你检查大厅抽屉时，备用钥匙不见了。\n\n\"谁最后用过备用钥匙？\"\n\n陈夫人回忆说，三天前她曾看到赵明辉在大厅抽屉附近徘徊。\n\n另外，老周提到一个细节：案发当晚，陈远山照例要喝威士忌。老周把酒和药瓶一起放在书桌上后就离开了。大约十五分钟后，他听到书房方向传来玻璃碎裂的声音——可能就是酒杯被打翻的声音。\n\n这十五分钟，是案件的关键时间窗口。","is_random":0,"is_ending":0,"choices":[
      {"text":"推算时间线——十五分钟窗口内每个人的行踪【隐藏选项】","target_scene":31,"hp_change":-3,"clue_change":15,"item_gain":"时间线分析","item_required":"指纹比对报告","is_hidden":1,"hidden_min_clue":45,"required_visited":[9,19]},
      {"text":"质问赵明辉关于失踪的备用钥匙","target_scene":21,"hp_change":-5,"clue_change":8,"item_gain":"","item_required":"","is_hidden":0,"hidden_min_clue":0}
    ]},
    {"id":29,"location":"老城区·追踪神秘访客","atmosphere":"悬疑","description":"你循着线索来到老城区。在一栋老旧公寓楼的信箱上，你找到了那个熟悉的符号——圆圈中的三角形。\n\n房东告诉你，302室的租客是一个三十多岁的男子，走路有点跛，上个月刚搬来。平时深居简出，很少与人交往。\n\n你用备用钥匙打开了302室的门。房间简陋但整洁。墙上贴满了关于陈远山的新闻报道和照片——这是长达数年的监视和调查。\n\n桌上有一本日记。翻开最后一页，上面写着：\n\n\"今晚，一切都会结束。二十年的等待，父亲，我终于可以为你做点什么了。我会让他在恐惧中死去，就像当年你在绝望中离开一样。但我不会杀他——我要让他活着，活在被揭露的耻辱中。毒药只是警告。真正毁掉他的，将是真相。\"\n\n日记的日期是今天。\n\n所以——神秘访客的意图不是杀人，而是揭露和恐吓？那真正的凶手是谁？","is_random":0,"is_ending":0,"choices":[
      {"text":"带着日记返回豪宅——神秘访客不是凶手，真凶另有其人","target_scene":31,"hp_change":-10,"clue_change":20,"item_gain":"决定性证据","item_required":"管家供词","is_hidden":1,"hidden_min_clue":45,"required_visited":[9,19]}
    ]},
    {"id":30,"location":"陈氏豪宅·大厅","atmosphere":"紧张","description":"经过漫长的调查，你决定做出最终判断。所有嫌疑人被召集到大厅。\n\n暴雨渐歇，天边露出了第一缕晨光。你站在大厅中央，面对五位神色各异的嫌疑人。\n\n管家老周双手紧握，额头渗汗。\n陈夫人低着头，不敢直视任何人。\n赵明辉烦躁地松了松领带。\n刘师傅靠着墙壁，面色苍白。\n而那个神秘访客——你虽然尚未找到他本人，但已经掌握了他的全部故事。\n\n真相只有一个。\n\n你深吸一口气，准备揭开雨夜密室杀人案的真相。","is_random":0,"is_ending":1,"choices":[
      {"text":"指认管家老周为凶手——他贪污被发现，铤而走险","target_scene":100,"hp_change":-3,"clue_change":0,"item_gain":"","item_required":"","is_hidden":0,"hidden_min_clue":0},
      {"text":"指认陈夫人和赵明辉合谋——为保险金和秘密关系","target_scene":100,"hp_change":-3,"clue_change":0,"item_gain":"","item_required":"","is_hidden":0,"hidden_min_clue":0},
      {"text":"指认神秘访客韩某——为父报仇，精心策划","target_scene":100,"hp_change":-3,"clue_change":0,"item_gain":"","item_required":"","is_hidden":0,"hidden_min_clue":0},
      {"text":"揭示真相——这是一场多人交织的悲剧，真正的凶手在意外之处【隐藏选项】","target_scene":100,"hp_change":-3,"clue_change":0,"item_gain":"","item_required":"决定性证据","is_hidden":1,"hidden_min_clue":60}
    ]},
    {"id":31,"location":"陈氏豪宅·大厅（综合推理）","atmosphere":"紧张","description":"所有线索在你脑海中汇聚。是时候做出最终的推理了。\n\n你回顾了整个案件的线索链：\n\n• 毒药瓶上有老周和刘师傅的指纹\n• 酒杯上有赵明辉的指纹\n• 花园里发现了神秘访客的鞋印\n• 亲子鉴定揭示了陈夫人与赵明辉的秘密\n• 韩某的日记表明他的目的是揭露而非杀人\n• 密室钥匙丢失，但门锁没有被撬\n• 毒药是植物提取的，来自温室\n\n一切证据指向一个复杂的真相——这不仅仅是一个凶手的罪行，而是多重动机交织的悲剧。每个人都有自己的秘密，而陈远山的死，是这些秘密碰撞的必然结果。\n\n关键问题是：谁是最后一个进入密室的人？谁在威士忌中下了毒？","is_random":0,"is_ending":0,"choices":[
      {"text":"最终指认——你已掌握足够线索，做出判断","target_scene":30,"hp_change":-3,"clue_change":0,"item_gain":"","item_required":"","is_hidden":0,"hidden_min_clue":0}
    ]},
    {"id":100,"location":"结局","atmosphere":"结局","description":"真相大白的时刻到了。","is_random":0,"is_ending":1,"choices":[]}
  ],
  "endings": [
    {"id":100,"type":"perfect","description":"你层层推理，证据链完整无缺。\n\n真相是：管家老周在陈远山的威士忌中下了毒——但不是氰化物，而是从刘师傅温室中获取的另一种慢性毒药。他本打算让陈远山在几天内慢慢病倒，为自己争取还钱的时间。\n\n但同一天晚上，赵明辉潜入书房与陈远山发生争执。在争执中，陈远山喝下了已被下毒的威士忌。赵明辉离开后，陈远山感到不适，服用了桌上的\"安眠药\"——但他不知道，神秘访客韩某早已将安眠药换成了氰化物，作为\"警告\"。\n\n两种毒药在陈远山体内产生了致命反应。氰化物迅速发作，陈远山在挣扎中打翻了酒杯，反锁了房门（他以为凶手还在外面），最终毒发身亡。\n\n老周、赵明辉、韩某——三人的行为交织在一起，共同导致了陈远山的死亡。\n\n你成功揭露了全部真相。老周被控投毒未遂，赵明辉因非法入侵和过失杀人被起诉，韩某被找到并因投毒罪被捕。\n\n正义得到了伸张，虽然过程曲折。","min_clue":70,"required_item":"决定性证据","required_hp":0,"suspect_flags":[0,4]},
    {"id":101,"type":"partial","description":"你的推理大部分正确——管家老周确实在威士忌中下了慢性毒药，而赵明辉在争执中加重了陈远山的病情。\n\n但你遗漏了一个关键细节：药瓶中被调换的安眠药。你将氰化物中毒归因于老周从温室获取的毒药，而忽略了神秘访客的存在。\n\n老周因投毒罪被判处有期徒刑。赵明辉因过失被从轻处理。陈夫人虽然失去了继承权，但避免了更严重的指控。\n\n神秘访客韩某——那个二十年前受害者的儿子——仍然逍遥法外。他在日记中写的\"真相\"尚未被公之于众。\n\n案件部分告破，但仍有未解之谜。","min_clue":45,"required_item":"","required_hp":0,"suspect_flags":[0]},
    {"id":102,"type":"wrong_accuse","description":"你被表面的证据误导了。\n\n你认定园丁刘师傅是凶手——他的温室种植了毒药来源植物，他的指纹出现在药瓶上，他有作案动机（被解雇的威胁）。\n\n刘师傅被逮捕，但他始终坚称自己无辜。一个月后，真正的凶手——管家老周——在企图潜逃时被抓获。老周供认了全部罪行。\n\n但为时已晚。刘师傅在拘留所中精神崩溃，而真正的幕后故事——神秘访客的存在——因错过了最佳调查时机而永远无法查明。\n\n你冤枉了一个无辜的人。作为一名警探，这是最沉重的失败。","min_clue":0,"required_item":"","required_hp":0,"suspect_flags":[3]},
    {"id":103,"type":"escape","description":"关键线索从你的指缝间溜走。\n\n你的调查支离破碎——没有足够的证据，没有完整的推理链。你无法确定谁是真正的凶手，只能让所有人都暂时离开。\n\n三天后，管家老周被发现死在自己的公寓中——死因是氰化物中毒。现场留下了一封信，署名是那个圆圈中的三角形符号。\n\n信上只有一句话：\"这只是开始。\"\n\n神秘访客仍在暗处，而你已经失去了所有线索。案件被无限期置，成为悬案。\n\n雨夜的真相，也许永远不会有人知道了。","min_clue":0,"required_item":"","required_hp":0,"suspect_flags":[]},
    {"id":104,"type":"twist","description":"当你以为案件告破时，一封匿名信揭示了一个更大的阴谋。\n\n你成功证明管家老周在威士忌中下了慢性毒药，赵明辉在争执中无意间加重了病情，而神秘访客韩某调换了安眠药——三人的行为共同导致了陈远山的死亡。\n\n但匿名信的内容让你毛骨悚然：\n\n\"你以为事情结束了吗？陈远山只是第一个。当年参与那场欺诈案的所有人，都会付出代价。下一个目标已经锁定。而你——警探林正——你的父亲，也是当年欺诈案的法律顾问。你确定要追查下去吗？\"\n\n你的父亲？二十年前的案件？\n\n你回想起父亲在你小时候曾经酗酒，曾说过一些关于\"做了错事\"的醉话。他三年前已去世，但这些话现在有了全新的含义。\n\n原来——你和这个案件，早在二十年前就已经被命运联系在了一起。\n\n案件结束了吗？不，这只是更大真相的序幕。","min_clue":60,"required_item":"神秘密信","required_hp":0,"suspect_flags":[4]}
  ]
};
